secret:
  enabled: true
  name: openstack-cloud-config
  create: false
nodeSelector:
  node-role.kubernetes.io/control-plane: "true"
tolerations:
  - key: node.cloudprovider.kubernetes.io/uninitialized
    value: "true"
    effect: NoSchedule
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    effect: NoSchedule